PCI: dwc: rcar-gen5: Update to fix style issues from PCIe4 reported by checkpatch
Fix coding style error flag by checkpatch.pl script:
ERROR: space required after that ',' (ctx:VxV)
+       mask = GENMASK(7,6);
                        ^

Signed-off-by: Thanh Le <thanh.le.wm@bp.renesas.com>