can: rcar_canfd: Fix build error caused by is_gen4()
is_gen4() is undefined because it was modified by commit: f0b37f2cb224 ("can: rcar_canfd: Add sh variable to
struct rcar_canfd_hw_info").
This replaces is_gen4() with 'gpriv->info->shared_can_regs'.

```
drivers/net/can/rcar/rcar_canfd.c: In function ‘rcar_canfd_reset_controller’:
drivers/net/can/rcar/rcar_canfd.c:874:14: error: implicit declaration of function ‘is_gen4’ [-Wimplicit-function-declaration]
  874 |         if (!is_gen4(gpriv)) {
      |              ^~~~~~~
drivers/net/can/rcar/rcar_canfd.c: At top level:
```

Fixes: f88ba5098e83 ("can: rcar_canfd: Fix CAN-FD mode as default")
Signed-off-by: Nobuhiro Iwamatsu <nobuhiro.iwamatsu.x90@mail.toshiba>
Reviewed-by: Biju Das <biju.das.jz@bp.renesas.com>